Fix issue mentioned in https://github.com/celery/celery/issues/1671
See the comment from @lance-burton on June 20, 2014.

A nested group in an expression such as:
c = (group(add.s(1,1),add.s(2,2))
     | add.s(1)
     | add.s(1)
     | group(mul.s(1),mul.s(2)))
res = c.apply_async().get()

Causes an "AttributeError: 'dict' object has no attribute 'type'".